apiVersion: v1
kind: Service
metadata:
  name: {{ include "rutorrent.fullname" . }}-ui
  labels:
    {{- include "rutorrent.labels" . | nindent 4 }}
    {{- if .Values.service.ui.labels }}
    {{ toYaml .Values.service.ui.labels | indent 4 }}
    {{- end }}
{{- with .Values.service.ui.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if (or (eq .Values.service.ui.type "ClusterIP") (empty .Values.service.ui.type)) }}
  type: ClusterIP
  {{- if .Values.service.ui.clusterIP }}
  clusterIP: {{ .Values.service.ui.clusterIP }}
  {{end}}
{{- else if eq .Values.service.ui.type "LoadBalancer" }}
  type: {{ .Values.service.ui.type }}
  {{- if .Values.service.ui.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.ui.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.ui.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.ui.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.service.ui.type }}
{{- end }}
{{- if .Values.service.ui.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.ui.externalIPs | indent 4 }}
{{- end }}
  {{- if .Values.service.ui.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.ui.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.ui.port }}
      protocol: TCP
      targetPort: http
      {{- if (and (eq .Values.service.ui.type "NodePort") (not (empty .Values.service.ui.nodePort))) }}
      nodePort: {{ .Values.service.ui.nodePort }}
      {{- end }}
  selector:
    {{- include "rutorrent.selectorLabels" . | nindent 4 }}
